autenticacao/urls.py
from django.urls import path
from . import views

app_name = 'autenticacao'

urlpatterns = [
    path('', views.login, name='login'),
    path("get_perfis/", views.get_perfis, name="get_perfis"),
    path("logout/", views.logout, name="logout"),
    path("esqueci_senha/", views.esqueci_senha, name="esqueci_senha"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

#aqui permite que o django possa acessar a urls de outros apps
urlpatterns = [
    path('', include('autenticacao.urls')),
    path('core/', include('core.urls')),
    path('cadastros/', include('cadastros.urls')),
]

core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    path("main", views.main, name="main"),
]

autenticacao/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User

from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http import JsonResponse
from cadastros.models import Usuario
from django.http import HttpResponse

def login(request):
    if request.method == 'POST':
        email = request.POST.get('txtEmail')
        senha = request.POST.get('txtSenha')
        perfil_id = request.POST.get('slcPerfil')

        usuario = authenticate(request, username=email, password=senha) #checagem de autenticacao
        
        if usuario is not None and perfil_id:
            perfis_usuario = usuario.perfis.filter(id=perfil_id)
            if perfis_usuario.exists():
                #limpa as sessoes do usuario
                request.session.flush()
                #cria a sessao do usuario
                auth_login(request, usuario)
                
                #armazenando na sessão
                request.session['id_atual'] = usuario.id
                request.session['email_atual'] = usuario.email
                request.session['departamento_id_atual'] = usuario.departamento.id
                request.session['departamento_nome_atual'] = usuario.departamento.nome
                request.session['departamento_sigla_atual'] = usuario.departamento.sigla                      
                request.session['perfil_atual'] = perfis_usuario.first().nome                
                request.session['perfis'] = list(usuario.perfis.values_list('nome', flat=True))
                
                #configura sessao para expirar em 4 horas
                request.session.set_expiry(14400)
                
                messages.success(request, 'Login realizado com sucesso!')
                
                #no futuro iremos separar em diferentes paginas
                if request.session.get('perfil_atual') in {'Administrador', 'Estoquista', 'Vendedor'}:
                    return redirect('core:main')
                
            else:
                messages.error(request, 'Perfil inválido para este usuário.')
        else:
            if usuario is None:
                messages.error(request, 'Senha incorreta.')
            else:
                messages.error(request, 'Usuário ou senha inválidos.')
            
    return render(request, 'login.html')

def get_perfis(request):
    email = request.GET.get('email', '')
    perfis = []
    if Usuario.objects.filter(email=email).exists():
        usuario = Usuario.objects.get(email=email)
        perfis = usuario.perfis.all().values('id', 'nome')
        data = {'perfis': list(perfis), 'usuario_existe': True}
    else:
        data = {'usuario_existe': False}
    return JsonResponse(data)

def logout(request):
    #limpa a sessao ao deslogar
    request.session.flush()
    auth_logout(request)
    
    messages.success(request, 'Logout realizado com sucesso.')
    return redirect('autenticacao:login')

def esqueci_senha(request):

    if request.method == 'POST':
        
        email = request.POST.get('txtEmail')
        senha = request.POST.get('txtNovaSenha')

        try:
            #busca o email no banco, "select por email"
            usuario = Usuario.objects.get(email=email)
            
            #se encontrar redefine a senha
            usuario.set_password(senha)
            usuario.save()

            messages.success(request, "Senha alterada com sucesso!")
            return redirect('autenticacao:login')
        
        #pega o erro e trata ele exibindo na tela isso ai
        except Usuario().DoesNotExist: 
            messages.error(request, "Esse e-mail não está registrado.")
            
        
    return render(request, 'esqueci_senha.html')

autenticacao/templates/esqueci_senha.html
{% extends 'index.html' %}

{% block conteudo %}
<div class="container">
    <h2>Esqueci minha senha</h2>
    <form method="POST" action="{% url 'autenticacao:esqueci_senha' %}" id="redefSenha">
        {% csrf_token %}
        <div class="form-group">
            <label for="txtEmail">E-mail</label>
            <input type="email" class="form-control" id="txtEmail" name="txtEmail" required autocomplete="off">
        </div>

        <div class="form-group" id="divSenha1">
            <label for="txtNovaSenha">Senha</label>
            <input type="password" class="form-control" id="txtNovaSenha" name="txtNovaSenha" required>
        </div>

        <div class="form-group" id="divSenha2">
            <label for="txtNovaSenha2">Confirme sua senha</label>
            <input type="password" class="form-control" id="txtNovaSenha2" name="txtNovaSenha2" required>
            <div id="divSenhaError" style="display: none;">As senhas não coincidem.</div>
        </div>
        <div id="divSpace" class="space"> </div>
        <button type="submit" class="btn btn-light">Enviar</button>
    </form>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    document.getElementById('redefSenha').addEventListener('submit', function(event) {
        const senha1 = document.getElementById('txtNovaSenha').value;
        const senha2 = document.getElementById('txtNovaSenha2').value;
        const mensagemErro = document.getElementById('divSenhaError');

        if (senha1 !== senha2) {
            event.preventDefault();//impede o envio do formulário
            mensagemErro.style.display = 'block';
            mensagemErro.style.color = 'red';
        } 
    });
});
</script>

{% endblock %}

autenticacao/templates/login.html
{% extends 'index.html' %}

{% block conteudo %}
<div class="container">
    <h2>Login</h2>
    <form method="POST" action="{% url 'autenticacao:login' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="txtEmail">E-mail</label>
            <input type="email" class="form-control" id="txtEmail" name="txtEmail" required autocomplete="off">
            <div id="divEmailError" class="error-message"> </div>
        </div>
        <div class="form-group hidden-group" id="divSenha">
            <label for="txtSenha">Senha</label>
            <input type="password" class="form-control" id="txtSenha" name="txtSenha" required autocomplete="new-password">
        </div>
        <div class="form-group hidden-group" id="divPerfil">
            <label for="perfil">Perfil</label>
            <select class="form-control" id="slcPerfil" name="slcPerfil" required></select>
        </div>
        <div id="divSpace" class="space"> </div>
        <button type="submit" class="btn btn-light">Entrar</button>
        <a href="{% url 'autenticacao:esqueci_senha' %}" id="btnEsqueciSenha" class="btn btn-light">Esqueci minha senha</a>
    </form>
</div>

<script>
    $(document).ready(function() {
        $('#txtEmail').on('input', function() {
            var email = $(this).val();
            $('#divPerfil').addClass('hidden-group');
            $('#divSenha').addClass('hidden-group');
            $('#slcPerfil').empty();
            $('#divEmailError').text(' ').removeClass('visible');

            if (email.length > 0) {
                $.ajax({
                    url: "{% url 'autenticacao:get_perfis' %}",
                    data: {'email': email},
                    success: function(data) {
                        if (data.usuario_existe) {
                            if (data.perfis.length > 0) {
                                $('#slcPerfil').empty();
                                data.perfis.forEach(function(perfil) {
                                    $('#slcPerfil').append(new Option(perfil.nome, perfil.id));
                                });
                                $('#divPerfil').removeClass('hidden-group');
                                $('#divSenha').removeClass('hidden-group');
                            } else {
                                toastr.error("Nenhum perfil encontrado para este e-mail.", "Erro");
                            }
                        } else {
                            $('#divEmailError').text('.').addClass('visible');
                        }
                    }
                });
            }
        });

        //$('#btnEsqueciSenha').click(function(event) {
        //    event.preventDefault();
        //    toastr.info('Se você esqueceu sua senha contate o administrador do sistema.');
        //});
    });
</script>
{% endblock %}